import { PDFDocument } from "pdf-lib";

export async function generatePdfLibPdfAsync(useObjectStreams: boolean = false): Promise<Buffer> {
    const pdfDoc = await PDFDocument.create();
    pdfDoc.setProducer('SignPdfLib');
    pdfDoc.setCreator('SignPdfLib');
    pdfDoc.setCreationDate(new Date(2023, 1, 23, 9, 0, 0));
    pdfDoc.setModificationDate(new Date(2023, 1, 23, 9, 0, 0));

    const page = pdfDoc.addPage();
    const fontSize = 10;
    page.drawText('PDF signing test document generated by PDFLib.', {
        x: 50,
        y: page.getSize().height - 4 * fontSize,
        size: fontSize
    });

    return Buffer.from(await pdfDoc.save({ useObjectStreams }));
}
